<?php

namespace Database\Factories;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Todo>
 */
class TodoFactory extends Factory
{
    protected $todos = [
        "Buy groceries",
        "Schedule doctor's appointment",
        "Finish the report",
        "Call John",
        "Pay bills",
        "Clean the house",
        "Go for a run",
        "Read a book",
        "Learn to play guitar",
        "Plan vacation",
        "Walk the dog",
        "Water the plants",
        "Do laundry",
        "Fold clothes",
        "Empty the dishwasher",
        "Take out the trash",
        "Recycle",
        "Fix the broken lamp",
        "Return library books",
        "Make a doctor's appointment",
        "Schedule a haircut",
        "Buy birthday gifts",
        "Write thank-you notes",
        "Send birthday cards",
        "Update resume",
        "Apply for jobs",
        "Make dinner reservations",
        "Book a flight",
        "Pack for the trip",
        "Go to the gym",
        "Meditate",
        "Journal",
        "Practice yoga",
        "Learn a new language",
        "Cook a new recipe",
        "Bake a cake",
        "Watch a movie",
        "Listen to music",
        "Go for a hike",
        "Visit friends",
        "Go to the park",
        "Attend a concert",
        "Go to the beach",
        "Go shopping",
        "Organize the garage",
        "Declutter the closet",
        "Fix the leaky faucet",
        "Change the air filter",
        "Mow the lawn",
        "Weed the garden",
        "Feed the birds",
        "Research a new hobby",
        "Learn a new skill",
        "Take online courses",
        "Attend a workshop",
        "Volunteer at a local charity",
        "Donate clothes",
        "Donate food",
        "Help a neighbor",
        "Spend time with family",
        "Play board games",
        "Play video games",
        "Go to a museum",
        "Go to the zoo",
        "Visit an art gallery",
        "Attend a sporting event",
        "Go to a festival",
        "Have a picnic",
        "Go stargazing",
        "Have a game night",
        "Have a movie night",
        "Read the news",
        "Check email",
        "Pay bills online",
        "Schedule appointments online",
        "Order groceries online",
        "Back up files",
        "Update software",
        "Clean the computer",
        "Organize photos",
        "Write in a journal",
        "Meditate",
        "Practice mindfulness",
        "Listen to relaxing music",
        "Take a deep breath",
        "Stretch",
        "Do some deep breathing exercises",
        "Practice gratitude",
        "Spend time in nature",
        "Connect with loved ones",
        "Help others",
        "Learn something new",
        "Challenge yourself",
        "Be kind to yourself",
        "Take a break",
        "Enjoy the moment",
        "Appreciate the little things",
        "Live in the present",
        "Be grateful for what you have",
        "Focus on your goals",
        "Believe in yourself",
        "Never give up",
        "Keep learning and growing",
        "Strive for excellence",
        "Be the best version of yourself",
        "Make a difference in the world",
        "Live a fulfilling life",
        "Be happy",
        "Be healthy",
        "Be successful",
        "Be kind",
        "Be compassionate",
        "Be understanding",
        "Be forgiving",
        "Be patient",
        "Be positive",
        "Be optimistic",
        "Be grateful",
        "Be mindful",
        "Be present",
        "Be yourself",
        "Love yourself",
        "Love others",
        "Love life",
    ];

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'todo' => fake()->randomElement($this->todos),
            'user_id' => User::factory(),
            'is_done' => false,
            'is_hidden' => false,
        ];
    }
}
